In [1]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

In [2]:
temperature=pd.read_excel("./暑假培训第四题（8.15-17）/附件2(Attachment 2).xlsx",sheet_name=0)

In [3]:
temperature["date"]=pd.to_datetime(pd.to_datetime(temperature["时间 (Time)"],format="%m-%d-%Y").dt.strftime("%Y-%m-%d"))
temperature
'''%qtconsole取出年月日  example：date=2022-01-25.........'''

'%qtconsole取出年月日  example：date=2022-01-25.........'

In [4]:
temperature=temperature.groupby("date").mean()
'''"一天有具体的时间点的对映不同温度，取一天所有温度的平均值，，，共74天，平均一天记录温度104029/74=1405.7972972972973次'''

'"一天有具体的时间点的对映不同温度，取一天所有温度的平均值，，，共74天，平均一天记录温度104029/74=1405.7972972972973次'

In [5]:
temperature

系统I温度 (Temperature of system I)  系统II温度 (Temperature of system II)
date                                                                          
2022-01-25                      1378.853377                         955.675052
2022-01-26                      1404.817708                         943.595729
2022-01-27                      1016.714986                         861.417375
2022-01-28                       601.506435                         779.863899
2022-01-29                      1055.616887                         782.035552
...                                     ...                                ...
2022-04-03                       814.740889                         797.645847
2022-04-04                       471.278949                         656.072465
2022-04-05                       764.303243                         785.466132
2022-04-06                       591.403870                         641.759421
2022-04-07                       507.772234                         631.842053

[73 rows x 2 columns]

In [6]:
temperature.isnull().sum()

系统I温度 (Temperature of system I)      0
系统II温度 (Temperature of system II)    0
dtype: int64

In [7]:
quality=pd.read_excel("./暑假培训第四题（8.15-17）/附件2(Attachment 2).xlsx",sheet_name=1)
paramter=pd.read_excel("./暑假培训第四题（8.15-17）/附件2(Attachment 2).xlsx",sheet_name=2)
process=pd.read_excel("./暑假培训第四题（8.15-17）/附件2(Attachment 2).xlsx",sheet_name=3)

In [8]:
import datetime
quality["dt"]=quality["时间 (Time)"].apply(lambda x:x-datetime.timedelta(hours=2))

In [9]:
quality

时间 (Time)  指标A (index A)  指标B (index B)  指标C (index C)  \
0    2022-01-25 00:50:00          78.31          23.66          12.24   
1    2022-01-25 01:50:00          78.46          23.88          12.41   
2    2022-01-25 02:50:00          79.08          23.52          12.41   
3    2022-01-25 03:50:00          79.29          22.94          11.72   
4    2022-01-25 04:50:00          79.95          21.42          10.68   
...                  ...            ...            ...            ...   
1739 2022-04-07 19:50:00          79.82          23.84          11.03   
1740 2022-04-07 20:50:00          78.98          25.36          11.37   
1741 2022-04-07 21:50:00          78.86          25.40          11.37   
1742 2022-04-07 22:50:00          79.10          25.58          11.37   
1743 2022-04-07 23:50:00          79.32          24.82          11.03   

      指标D (index D)                  dt  
0             17.81 2022-01-24 22:50:00  
1             17.99 2022-01-24 23:50:00  
2             17.86 2022-01-25 00:50:00  
3             17.86 2022-01-25 01:50:00  
4             17.63 2022-01-25 02:50:00  
...             ...                 ...  
1739          13.52 2022-04-07 17:50:00  
1740          12.85 2022-04-07 18:50:00  
1741          11.42 2022-04-07 19:50:00  
1742          11.55 2022-04-07 20:50:00  
1743          11.55 2022-04-07 21:50:00  

[1744 rows x 6 columns]

In [10]:
quality.drop(quality.index[0:2],inplace=True)#删除1-25以前的数据
quality

时间 (Time)  指标A (index A)  指标B (index B)  指标C (index C)  \
2    2022-01-25 02:50:00          79.08          23.52          12.41   
3    2022-01-25 03:50:00          79.29          22.94          11.72   
4    2022-01-25 04:50:00          79.95          21.42          10.68   
5    2022-01-25 05:50:00          80.20          21.20          10.16   
6    2022-01-25 06:50:00          80.38          20.75          10.16   
...                  ...            ...            ...            ...   
1739 2022-04-07 19:50:00          79.82          23.84          11.03   
1740 2022-04-07 20:50:00          78.98          25.36          11.37   
1741 2022-04-07 21:50:00          78.86          25.40          11.37   
1742 2022-04-07 22:50:00          79.10          25.58          11.37   
1743 2022-04-07 23:50:00          79.32          24.82          11.03   

      指标D (index D)                  dt  
2             17.86 2022-01-25 00:50:00  
3             17.86 2022-01-25 01:50:00  
4             17.63 2022-01-25 02:50:00  
5             16.92 2022-01-25 03:50:00  
6             15.75 2022-01-25 04:50:00  
...             ...                 ...  
1739          13.52 2022-04-07 17:50:00  
1740          12.85 2022-04-07 18:50:00  
1741          11.42 2022-04-07 19:50:00  
1742          11.55 2022-04-07 20:50:00  
1743          11.55 2022-04-07 21:50:00  

[1742 rows x 6 columns]

In [11]:
def qualified(quality):
    if (quality["指标A (index A)"]>=77.78 and quality["指标B (index B)"]<=80.33 and quality["指标C (index C)"]<24.15 and quality["指标D (index D)"]<15.62):
        return 1
    else:
        return 0

In [12]:
quality["合格 (qualified)"]=quality.apply(lambda quality:qualified(quality),axis=1)
quality

时间 (Time)  指标A (index A)  指标B (index B)  指标C (index C)  \
2    2022-01-25 02:50:00          79.08          23.52          12.41   
3    2022-01-25 03:50:00          79.29          22.94          11.72   
4    2022-01-25 04:50:00          79.95          21.42          10.68   
5    2022-01-25 05:50:00          80.20          21.20          10.16   
6    2022-01-25 06:50:00          80.38          20.75          10.16   
...                  ...            ...            ...            ...   
1739 2022-04-07 19:50:00          79.82          23.84          11.03   
1740 2022-04-07 20:50:00          78.98          25.36          11.37   
1741 2022-04-07 21:50:00          78.86          25.40          11.37   
1742 2022-04-07 22:50:00          79.10          25.58          11.37   
1743 2022-04-07 23:50:00          79.32          24.82          11.03   

      指标D (index D)                  dt  合格 (qualified)  
2             17.86 2022-01-25 00:50:00               0  
3             17.86 2022-01-25 01:50:00               0  
4             17.63 2022-01-25 02:50:00               0  
5             16.92 2022-01-25 03:50:00               0  
6             15.75 2022-01-25 04:50:00               0  
...             ...                 ...             ...  
1739          13.52 2022-04-07 17:50:00               1  
1740          12.85 2022-04-07 18:50:00               1  
1741          11.42 2022-04-07 19:50:00               1  
1742          11.55 2022-04-07 20:50:00               1  
1743          11.55 2022-04-07 21:50:00               1  

[1742 rows x 7 columns]

In [13]:
quality["date"]=pd.to_datetime(pd.to_datetime(quality["时间 (Time)"],format="%m-%d-%Y").dt.strftime("%Y-%m-%d"))

'''%qtconsole取出年月日  example：date=2022-01-25.........'''
quality=quality.groupby("date").mean()
'''"一天有具体的时间点的对映不同温度，取一天所有温度的平均值，，，共74天，平均一天记录温度104029/74=1405.7972972972973次'''

'"一天有具体的时间点的对映不同温度，取一天所有温度的平均值，，，共74天，平均一天记录温度104029/74=1405.7972972972973次'

In [14]:
quality_ed=quality.groupby("date")["合格 (qualified)"].mean()
quality_ed

date
2022-01-25    0.181818
2022-01-26    0.208333
2022-01-27    0.000000
2022-01-28    0.458333
2022-01-29    0.125000
                ...   
2022-04-03    1.000000
2022-04-04    1.000000
2022-04-05    1.000000
2022-04-06    0.833333
2022-04-07    0.958333
Name: 合格 (qualified), Length: 73, dtype: float64

In [15]:
process["date"]=pd.to_datetime(pd.to_datetime(process["时间 (Time)"],format="%m-%d-%Y").dt.strftime("%Y-%m-%d"))

'''%qtconsole取出年月日  example：date=2022-01-25.........'''
process=process.groupby("date").mean()
'''一天有具体的时间点的对映不同温度，取一天所有温度的平均值，，，共74天，平均一天记录温度104029/74=1405.7972972972973次'''
process

过程数据1 (Process parameter 1)  过程数据2 (Process parameter 2)  \
date                                                                   
2022-01-25                         1.25                         3.09   
2022-01-26                         1.25                         3.09   
2022-01-27                         1.25                         3.09   
2022-01-28                         1.25                         3.09   
2022-01-29                         1.25                         3.09   
...                                 ...                          ...   
2022-04-07                         1.25                         3.09   
2022-04-08                         1.25                         3.09   
2022-04-09                         1.25                         3.09   
2022-04-10                         1.25                         3.09   
2022-04-11                         1.25                         3.09   

            过程数据3 (Process parameter 3)  过程数据4 (Process parameter 4)  
date                                                                  
2022-01-25                   235.346250                   157.388750  
2022-01-26                   240.648750                   153.235000  
2022-01-27                   247.526250                   155.666250  
2022-01-28                   257.313750                   147.592500  
2022-01-29                   268.251250                   149.742500  
...                                 ...                          ...  
2022-04-07                   296.355556                   147.936667  
2022-04-08                   315.613750                   141.091250  
2022-04-09                   281.596667                   155.241111  
2022-04-10                   278.377500                   155.655000  
2022-04-11                   269.025000                   157.950000  

[77 rows x 4 columns]

In [16]:
paramter.columns
paramter.columns=['date', '原矿参数1 (Mineral parameter 1)',
       '原矿参数2 (Mineral parameter 2)', '原矿参数3 (Mineral parameter 3)',
       '原矿参数4 (Mineral parameter 4)']
paramter.set_index(keys="date",inplace=True,drop=True)

In [17]:
data3=pd.concat([temperature,quality,paramter,process],axis=1)
data3

系统I温度 (Temperature of system I)  \
date                                          
2022-01-25                      1378.853377   
2022-01-26                      1404.817708   
2022-01-27                      1016.714986   
2022-01-28                       601.506435   
2022-01-29                      1055.616887   
...                                     ...   
2022-04-07                       507.772234   
2022-04-08                              NaN   
2022-04-09                              NaN   
2022-04-10                              NaN   
2022-04-11                              NaN   

            系统II温度 (Temperature of system II)  指标A (index A)  指标B (index B)  \
date                                                                          
2022-01-25                         955.675052      79.275455      23.095455   
2022-01-26                         943.595729      79.099583      23.828750   
2022-01-27                         861.417375      78.414167      24.445833   
2022-01-28                         779.863899      79.134583      24.636250   
2022-01-29                         782.035552      78.762917      24.308333   
...                                       ...            ...            ...   
2022-04-07                         631.842053      79.139167      24.835000   
2022-04-08                                NaN            NaN            NaN   
2022-04-09                                NaN            NaN            NaN   
2022-04-10                                NaN            NaN            NaN   
2022-04-11                                NaN            NaN            NaN   

            指标C (index C)  指标D (index D)  合格 (qualified)  \
date                                                       
2022-01-25      11.263636      17.269091        0.181818   
2022-01-26      10.733333      17.205833        0.208333   
2022-01-27      13.994583      18.479583        0.000000   
2022-01-28      12.746250      16.390417        0.458333   
2022-01-29      12.674167      16.960000        0.125000   
...                   ...            ...             ...   
2022-04-07      11.177500      12.989583        0.958333   
2022-04-08            NaN            NaN             NaN   
2022-04-09            NaN            NaN             NaN   
2022-04-10            NaN            NaN             NaN   
2022-04-11            NaN            NaN             NaN   

            原矿参数1 (Mineral parameter 1)  原矿参数2 (Mineral parameter 2)  \
date                                                                   
2022-01-25                        55.26                       108.03   
2022-01-26                        55.28                       102.38   
2022-01-27                        54.04                       102.21   
2022-01-28                        56.43                       112.74   
2022-01-29                        54.89                       109.21   
...                                 ...                          ...   
2022-04-07                        54.40                       105.14   
2022-04-08                        52.88                        91.27   
2022-04-09                        54.44                        92.12   
2022-04-10                        56.27                       111.38   
2022-04-11                        56.71                       111.46   

            原矿参数3 (Mineral parameter 3)  原矿参数4 (Mineral parameter 4)  \
date                                                                   
2022-01-25                        43.29                        20.92   
2022-01-26                        46.13                        20.10   
2022-01-27                        47.94                        21.30   
2022-01-28                        43.54                        20.14   
2022-01-29                        43.60                        21.64   
...                                 ...                          ...   
2022-04-07                        49.03                        20.82   
2022-0

In [18]:
data3.isnull().sum()

系统I温度 (Temperature of system I)      4
系统II温度 (Temperature of system II)    4
指标A (index A)                        4
指标B (index B)                        4
指标C (index C)                        4
指标D (index D)                        4
合格 (qualified)                       4
原矿参数1 (Mineral parameter 1)          0
原矿参数2 (Mineral parameter 2)          0
原矿参数3 (Mineral parameter 3)          0
原矿参数4 (Mineral parameter 4)          0
过程数据1 (Process parameter 1)          0
过程数据2 (Process parameter 2)          0
过程数据3 (Process parameter 3)          0
过程数据4 (Process parameter 4)          0
dtype: int64

In [19]:
data3

系统I温度 (Temperature of system I)  \
date                                          
2022-01-25                      1378.853377   
2022-01-26                      1404.817708   
2022-01-27                      1016.714986   
2022-01-28                       601.506435   
2022-01-29                      1055.616887   
...                                     ...   
2022-04-07                       507.772234   
2022-04-08                              NaN   
2022-04-09                              NaN   
2022-04-10                              NaN   
2022-04-11                              NaN   

            系统II温度 (Temperature of system II)  指标A (index A)  指标B (index B)  \
date                                                                          
2022-01-25                         955.675052      79.275455      23.095455   
2022-01-26                         943.595729      79.099583      23.828750   
2022-01-27                         861.417375      78.414167      24.445833   
2022-01-28                         779.863899      79.134583      24.636250   
2022-01-29                         782.035552      78.762917      24.308333   
...                                       ...            ...            ...   
2022-04-07                         631.842053      79.139167      24.835000   
2022-04-08                                NaN            NaN            NaN   
2022-04-09                                NaN            NaN            NaN   
2022-04-10                                NaN            NaN            NaN   
2022-04-11                                NaN            NaN            NaN   

            指标C (index C)  指标D (index D)  合格 (qualified)  \
date                                                       
2022-01-25      11.263636      17.269091        0.181818   
2022-01-26      10.733333      17.205833        0.208333   
2022-01-27      13.994583      18.479583        0.000000   
2022-01-28      12.746250      16.390417        0.458333   
2022-01-29      12.674167      16.960000        0.125000   
...                   ...            ...             ...   
2022-04-07      11.177500      12.989583        0.958333   
2022-04-08            NaN            NaN             NaN   
2022-04-09            NaN            NaN             NaN   
2022-04-10            NaN            NaN             NaN   
2022-04-11            NaN            NaN             NaN   

            原矿参数1 (Mineral parameter 1)  原矿参数2 (Mineral parameter 2)  \
date                                                                   
2022-01-25                        55.26                       108.03   
2022-01-26                        55.28                       102.38   
2022-01-27                        54.04                       102.21   
2022-01-28                        56.43                       112.74   
2022-01-29                        54.89                       109.21   
...                                 ...                          ...   
2022-04-07                        54.40                       105.14   
2022-04-08                        52.88                        91.27   
2022-04-09                        54.44                        92.12   
2022-04-10                        56.27                       111.38   
2022-04-11                        56.71                       111.46   

            原矿参数3 (Mineral parameter 3)  原矿参数4 (Mineral parameter 4)  \
date                                                                   
2022-01-25                        43.29                        20.92   
2022-01-26                        46.13                        20.10   
2022-01-27                        47.94                        21.30   
2022-01-28                        43.54                        20.14   
2022-01-29                        43.60                        21.64   
...                                 ...                          ...   
2022-04-07                        49.03                        20.82   
2022-0

In [20]:
data3.to_csv("第三问.csv")
data3.columns

Index(['系统I温度 (Temperature of system I)', '系统II温度 (Temperature of system II)',
       '指标A (index A)', '指标B (index B)', '指标C (index C)', '指标D (index D)',
       '合格 (qualified)', '原矿参数1 (Mineral parameter 1)',
       '原矿参数2 (Mineral parameter 2)', '原矿参数3 (Mineral parameter 3)',
       '原矿参数4 (Mineral parameter 4)', '过程数据1 (Process parameter 1)',
       '过程数据2 (Process parameter 2)', '过程数据3 (Process parameter 3)',
       '过程数据4 (Process parameter 4)'],
      dtype='object')

In [26]:
data3.dropna(inplace=True)#删除NaN值
#第四问测试数据
date=np.array([[341.40,665.04,52.88,91.2,47.22,22.26,1.25,3.09,315.613750,141.091250],
               [1010.32,874.47,54.44,92.12,48.85,21.83,1.25,3.09,281.596667,155.241111]])
x=data3[['系统I温度 (Temperature of system I)', '系统II温度 (Temperature of system II)',
       '原矿参数1 (Mineral parameter 1)',
       '原矿参数2 (Mineral parameter 2)', '原矿参数3 (Mineral parameter 3)',
       '原矿参数4 (Mineral parameter 4)', '过程数据1 (Process parameter 1)',
       '过程数据2 (Process parameter 2)', '过程数据3 (Process parameter 3)',
       '过程数据4 (Process parameter 4)']]
y=data3[['指标A (index A)', '指标B (index B)', '指标C (index C)', '指标D (index D)',
       '合格 (qualified)']]

In [27]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
import xgboost as xgb
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
# from sklearn.pipeline import Pipeline
# from sklearn.preprocessing import StandardScaler
# from sklearn.svm import SVC
# from sklearn.decomposition import PCA
m1=xgb.XGBRegressor()

m1.fit(x,y)
m2=LinearRegression()
m2.fit(x,y)
m3=RandomForestRegressor()
m3.fit(x,y)
m4=DecisionTreeRegressor()
m4.fit(x,y)
# m5=GradientBoostingRegressor()
# m5.fit(x,y)
m6=KNeighborsRegressor()
m6.fit(x,y)

print("xgbboost决定系数R^2:{},预测结果:{}".format(m1.score(x,y),m1.predict(date)))
print("LinearRegression决定系数R^2:{},预测结果:{}".format(m2.score(x,y),m2.predict(date)))
print("RandomForestRegressor决定系数R^2:{},预测结果:{}".format(m3.score(x,y),m3.predict(date)))
print("DecisionTreeRegressor决定系数R^2:{},预测结果:{}".format(m4.score(x,y),m4.predict(date)))
# print("GradientBoostingRegressor决定系数R^2:{},预测结果:{}".format(m5.score(x,y),m5.predict(date)))
print("KNeighborsRegressor决定系数R^2:{},预测结果:{}".format(m6.score(x,y),m6.predict(date)))

xgbboost决定系数R^2:0.9999979618705618,预测结果:[[78.33033    24.230349   11.313308   14.682371    0.5090681 ]
 [79.038025   24.580645   10.861326   14.067715    0.29223952]]
LinearRegression决定系数R^2:0.26463459358986635,预测结果:[[78.69239189 25.83131864 11.69330953 12.48073904  0.94632321]
 [79.10139765 23.92165249 10.61889316 14.19592848  0.71402914]]
RandomForestRegressor决定系数R^2:0.8557422009871338,预测结果:[[78.49885186 25.03803852 11.71003974 16.49146693  0.57108696]
 [78.89312194 24.35062982 11.33072512 14.83140584  0.61600155]]
DecisionTreeRegressor决定系数R^2:1.0,预测结果:[[79.20375    23.8425     11.30125    11.24416667  1.        ]
 [79.15666667 24.48708333 12.69625    17.47833333  0.33333333]]
KNeighborsRegressor决定系数R^2:0.33169084106243113,预测结果:[[78.70218083 24.92458498 11.95196212 15.27859848  0.7365942 ]
 [78.75416667 24.48008333 11.54191667 14.51791667  0.64166667]]


c:\users\taylor\appdata\roaming\microsoft\windows\start menu\programs\python 3.9\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
c:\users\taylor\appdata\roaming\microsoft\windows\start menu\programs\python 3.9\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\users\taylor\appdata\roaming\microsoft\windows\start menu\programs\python 3.9\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(
c:\users\taylor\appdata\roaming\microsoft\windows\start menu\programs\python 3.9\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


In [30]:
# 第四问  方法：一二三四问类似。一二问数据相同，三四问数据相同，只是每次预测的未知量不同。
predict_date=np.array([[0.8,56.27,111.38,7.52,20.26,1.25,3.09,278.377500,155.655000],     #预测数据
                       [0.99,56.71,111.46,46.67,18.48,1.25,3.09,269.025000,157.950000]])
X=data3[['合格 (qualified)',
       '原矿参数1 (Mineral parameter 1)',
       '原矿参数2 (Mineral parameter 2)', '原矿参数3 (Mineral parameter 3)',
       '原矿参数4 (Mineral parameter 4)', '过程数据1 (Process parameter 1)',
       '过程数据2 (Process parameter 2)', '过程数据3 (Process parameter 3)',
       '过程数据4 (Process parameter 4)']]
Y=data3[['系统I温度 (Temperature of system I)', '系统II温度 (Temperature of system II)','指标A (index A)', '指标B (index B)', '指标C (index C)', '指标D (index D)',]]
m11=xgb.XGBRegressor()
m11.fit(X,Y)
m22=LinearRegression()
m22.fit(X,Y)
m33=RandomForestRegressor()
m33.fit(X,Y)
m44=DecisionTreeRegressor()
m44.fit(X,Y)
# m5=GradientBoostingRegressor()
# m5.fit(x,y)
m66=KNeighborsRegressor()
m66.fit(X,Y)
np.set_printoptions(suppress=True)
print("xgbboost决定系数R^2:{},预测结果:{}".format(m11.score(X,Y),m11.predict(predict_date)))
print("LinearRegression决定系数R^2:{},预测结果:{}".format(m22.score(X,Y),m22.predict(predict_date)))
print("RandomForestRegressor决定系数R^2:{},预测结果:{}".format(m33.score(X,Y),m33.predict(predict_date)))
print("DecisionTreeRegressor决定系数R^2:{},预测结果:{}".format(m44.score(X,Y),m44.predict(predict_date)))
# print("GradientBoostingRegressor决定系数R^2:{},预测结果:{}".format(m5.score(x,y),m5.predict(date)))
print("KNeighborsRegressor决定系数R^2:{},预测结果:{}".format(m66.score(X,Y),m66.predict(predict_date)))


xgbboost决定系数R^2:0.9999990274841069,预测结果:[[729.2369   674.00146   78.894394  22.521627   9.973312  13.605254]
 [786.7671   826.4879    79.23659   23.59878   11.241638  13.295436]]
LinearRegression决定系数R^2:0.31638381116139785,预测结果:[[202.05327634 130.25289088  80.24844154  24.91068669  13.69736173
    9.68018663]
 [917.99450298 777.06897263  79.19084026  24.1459848   10.92635122
   12.07243644]]
RandomForestRegressor决定系数R^2:0.871810871356383,预测结果:[[754.31429133 740.70476761  79.03732955  24.51157538  11.4384072
   13.90337841]
 [970.8604345  819.06507527  79.18200455  24.05635455  10.90184053
   13.47612424]]
DecisionTreeRegressor决定系数R^2:1.0,预测结果:[[511.82760741 573.24029861  78.26791667  24.92833333  12.85333333
   16.98333333]
 [840.33367944 847.6613101   79.34458333  24.38458333  12.23291667
   14.07916667]]
KNeighborsRegressor决定系数R^2:0.1858773354462858,预测结果:[[ 900.04629919  759.56716312   78.79275      24.23375      12.096
    14.6615    ]
 [1087.99057142  853.23167533   78.805        2

c:\users\taylor\appdata\roaming\microsoft\windows\start menu\programs\python 3.9\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
c:\users\taylor\appdata\roaming\microsoft\windows\start menu\programs\python 3.9\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\users\taylor\appdata\roaming\microsoft\windows\start menu\programs\python 3.9\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(
c:\users\taylor\appdata\roaming\microsoft\windows\start menu\programs\python 3.9\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


In [39]:
a1=m11.predict(predict_date).round()
a1=a1[:,2:]
column=['指标A (index A)', '指标B (index B)', '指标C (index C)', '指标D (index D)']
a1=pd.DataFrame(a1,columns=column)
a1

指标A (index A)  指标B (index B)  指标C (index C)  指标D (index D)
0      78.894394      22.521627       9.973312      13.605254
1      79.236588      23.598780      11.241638      13.295436

In [43]:
#调用自定义函数qualified()

a1["合格 (qualified)"]=a1.apply(lambda a1:qualified(a1),axis=1)
a1

指标A (index A)  指标B (index B)  指标C (index C)  指标D (index D)  合格 (qualified)
0      78.894394      22.521627       9.973312      13.605254               1
1      79.236588      23.598780      11.241638      13.295436               1